[package]
name = "rust2pickle"
version = "0.0.0"
authors = ["Yijun Yu <yijun.yu@gmail.com>", "Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
syn-serde = { path = "../.." }
syn = { version = "1", features = ["full"] }
serde-pickle = "1.0"
