name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  codegen:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/gen.yml@931686d4e4cf88b13e790040727ccde2dba8ec62 # main
    permissions:
      contents: write # unused (used when creating branch for pr)
      pull-requests: write # unused (used in `codegen-automerge: true` case)
  miri:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/miri.yml@931686d4e4cf88b13e790040727ccde2dba8ec62 # main
    with:
      # NB: sync with test job's --exclude option
      args: --exclude syn-serde-internal-codegen
  msrv:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/msrv.yml@931686d4e4cf88b13e790040727ccde2dba8ec62 # main
  test:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/test.yml@931686d4e4cf88b13e790040727ccde2dba8ec62 # main
    with:
      # NB: sync with miri job's --exclude option
      test-args: --exclude syn-serde-internal-codegen
      no-std: false
      optional-deps: ''
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@931686d4e4cf88b13e790040727ccde2dba8ec62 # main
    permissions:
      security-events: write # for github/codeql-action/*
